### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user2",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user2",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###

# huske at sætte :
#Accept: application/json
#Authorization: Bearer {{jwt_token}}, på all endpoints der har security på

GET localhost:7007/api/trip
Accept: application/json
Authorization: Bearer {{jwt_token}}

###

GET localhost:7007/api/trip/0

###

POST http://localhost:7007/api/trip
Content-Type: application/json

{
  "id": 1,
  "startTime": [
    2024,
    11,
    4
  ],
  "endTime": [
    2024,
    12,
    1
  ],
  "startPosition": "KBH H",
  "name": "Japan",
  "price": 25000,
  "category": "CITY",
  "guide":{}

  }


###

PUT localhost:7007/api/trip/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 1,
  "startTime": [
    2024,
    11,
    4
  ],
  "endTime": [
    2024,
    12,
    1
  ],
  "startPosition": "KBH H",
  "name": "Japan",
  "price": 25000,
  "category": "CITY",
  "guide": {
    "id": 1,
    "firstName": "Sander",
    "lastName": "Jens",
    "email": "thisMail@Gmailcom",
    "phone": 0,
    "yearsOfExperience": 0,
    "trips": []
  }
}

###

DELETE localhost:7007/api/trip/0

###

PUT localhost:7007/api/trip/3/guides/1



